import { Center } from '@chakra-ui/react';
import { type NextPage } from 'next';
import Head from 'next/head';
import Maps from '~/components/Maps/Maps';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Home Page</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Center as="main">
				<Maps maps={<Maps.Object />} />
			</Center>
		</>
	);
};

export default Home;
