import { Center, Text } from '@chakra-ui/react';
import { UserButton, useAuth } from '@clerk/nextjs';
import { type NextPage } from 'next';
import Head from 'next/head';
import Maps from '~/components/Maps/Maps';

const Home: NextPage = () => {
	const { isSignedIn } = useAuth();
	return (
		<>
			<Head>
				<title>Home Page</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Center as="header" mx={36} h={20}>
				<Center
					as="nav"
					justifyContent="space-between"
					alignItems="center"
					w="100%"
				>
					<Text fontSize="2xl">LOGO</Text>
					{isSignedIn ? <UserButton /> : null}
				</Center>
			</Center>
			<Center as="main">
				<Maps maps={<Maps.Object />} />
			</Center>
		</>
	);
};

export default Home;
